### PR TITLE
Add some functionality to export zonefiles in bind format.

### PR DESCRIPTION
**Pull request by dlutzy**
This was added to the API and is very useful.  This change adds a function export_zone()

### CODE REVIEW

**Comment by dlutzy** [comment]
Hi.  I think the failing tests are due to an environment issue
    ULTRADNS_UNIT_TEST_USERNAME: 
    ULTRADNS_UNIT_TEST_PASSWORD: 
    ULTRADNS_UNIT_TEST_HOST_URL: 
 and not my code.  
(Although my code might be bad too!!)
thanks!

**Comment by stevedejong** [comment]
hello - this is a merge analysis issue with the test variables not getting set properly. we are working on getting that fixed.

Does not appear to be a code issue.  Human review didn't raise any flags.  We will merge asap.

Thank you very much for your contribution!

**Comment by stevedejong** [comment]
github actions don't allow the use of secrets when merging from a fork into master.

created a local branch, merged into that branch, then merged into main.  all tests passed.

will get this deployed to pypi.
thanks again for the cotribution

**Comment by dlutzy** [comment]
Thank you Steve, much appreciated.

**Pull request merged**
